### ISSUE TITLE
React veya angular2 gibi client-side kütüphanelerden birine ihtiyacımız var mı?

### ISSUE THREAD

**Issue by msusur** [CodeFiction/tech-radar#1]

**Comment by FiratOZ** [comment]
Bence **_reactjs_** kullanabiliriz.

**Comment by FiratOZ** [comment]
**_Angular_** de kullanabiliriz.

**Comment by FiratOZ** [comment]
Oylama gibi oldu :) React 2 oyla önde.

**Comment by msusur** [comment]
angular 2 epey iyi arkadaslar, cok hizli ve angular-cli cok tatli :)

**Comment by ozgunbal** [comment]
ben angular1 kullanmıştım, 2ye bakmadım ama yorumlar iyiydi. Onun dışında angular syntax'a çok ısınamadığımı söyleyeyim :D

**Comment by uguratar** [comment]
Angular 2 ve type script diyorum ben.

**Comment by ozaydinb** [comment]
angular 2 ve type script'e katılıyorum.

**Comment by melmanot** [comment]
angular 2 +  typescript bende varım.

**Comment by msusur** [comment]
angular 2 ve typescript kullanacagiz diye anlastik.
